In [44]:
#importação de bibliotecas sempre no inicio
import pandas as pd
import numpy as np #usado para conceitos Estatisticos

In [59]:
# === 1) Carregar base ===
df = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv', sep=';')
df['nada a ver'] = df['registro_ocorrencias'] + df['fase'] #resulta a soma das duas colunas
df
#print (df.head(6))
#print (df.descibre())
#print (df.tail(6))

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase,nada a ver
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,21,2,0,0,0,0,578,3,581
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,15,6,0,1,0,0,441,3,444
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,47,2,1,0,0,0,637,3,640
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,26,2,1,0,0,0,473,3,476
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,10,1,3,0,0,0,147,3,150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36898,159,10,2025,2025m10,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,0.0,37,2,0,0,0,0,163,2,165
36899,165,10,2025,2025m10,33,5,Mangaratiba,3302601,Interior,1,...,0.0,21,0,0,0,0,0,196,2,198
36900,166,10,2025,2025m10,33,5,Angra dos Reis,3300100,Interior,3,...,0.0,82,8,0,1,0,0,682,2,684
36901,167,10,2025,2025m10,43,5,Paraty,3303807,Interior,1,...,1.0,11,1,0,0,0,0,195,2,197
36902,168,10,2025,2025m10,28,5,Rio Claro,3304409,Interior,0,...,0.0,3,1,0,0,0,0,66,2,68

In [10]:
df_roubo_celular_dp = df.groupby('cisp')['roubo_celular'].sum().reset_index()
df_roubo_celular_dp =  df_roubo_celular_dp.sort_values(by='roubo_celular', ascending = False)
print(df_roubo_celular_dp)

     cisp  roubo_celular
52     59          13788
57     64          10421
30     34           9379
25     29           8807
2       5           7992
..    ...            ...
94    111              2
129   155              1
126   152              1
131   157              1
77     92              0

[138 rows x 2 columns]

In [ ]:
array_roubo_celular = np.array(array_roubo_celular['Valor de Venda']) #criação do Array

In [ ]:
#a Boa pratica sempre trabalha com esses valores de porcentagem nos quantis. Caso seja solicitado a alteração desses valores, 
#documentar de quem partiu a solicitação pois irá maquear os dados resultantes.

media = np.mean(array_roubo_celular)
mediana = np.median(array_roubo_celular)
q1 = np.quantile(array_roubo_celular, 0.25)
q2 = np.quantile(array_roubo_celular, 0.50)
q3 = np.quantile(array_roubo_celular, 0.75)

iqr = q3 - q1
limite_superior = q3 + (1.5 * iqr)
limite_inferior = q1 + (1.5 * iqr)

print(f'A média é {media}')
print(f'A mediana é {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, Mediana): {q2}')
print(f'Terceiro quartil (Q3): {q3}')
print(f'o valor do limite Superior é: {limite_superior}')
print(f'o valor do limite Inferior é: {limite_inferior}')

In [ ]:
outliers_roubo_celular = df.roubo.celular.loc['furto_celular'] > limite_superior]

In [60]:
reg_met = ["Rio de Janeiro", "Niterói", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Belford Roxo", "São João de Meriti", "Nilópolis", "Mesquita", "Queimados", "Japeri", "Paracambi"]
df_capital = df.loc[df['munic'].isin (reg_met)]
df_capital['veiculo'] = df_capital['furto_veiculos'] + df_capital['roubo_veiculo']
df_capital

C:\Users\bruno.tcruz\AppData\Local\Temp\ipykernel_18384\1948486649.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_capital['veiculo'] = df_capital['furto_veiculos'] + df_capital['roubo_veiculo']

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase,nada a ver,veiculo
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,21,2,0,0,0,0,578,3,581,17
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,15,6,0,1,0,0,441,3,444,18
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,47,2,1,0,0,0,637,3,640,39
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,26,2,1,0,0,0,473,3,476,44
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,10,1,3,0,0,0,147,3,150,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36832,76,10,2025,2025m10,12,4,Niterói,3303302,Grande Niterói,0,...,56,2,0,0,0,0,897,2,899,8
36833,77,10,2025,2025m10,12,4,Niterói,3303302,Grande Niterói,0,...,38,4,0,0,0,0,842,2,844,5
36834,78,10,2025,2025m10,12,4,Niterói,3303302,Grande Niterói,2,...,37,2,0,0,0,0,624,2,626,31
36835,79,10,2025,2025m10,12,4,Niterói,3303302,Grande Niterói,1,...,19,3,0,0,0,0,309,2,311,10
36836,81,10,2025,2025m10,12,4,Niterói,3303302,Grande Niterói,2,...,29,3,0,0,0,0,410,2,412,4

In [61]:
df_veiculo_capital = df_capital.groupby('cisp')['veiculo'].sum().reset_index()
df_veiculo_capital =  df_veiculo_capital.sort_values(by='veiculo', ascending = False)
df_veiculo_capital

    cisp  veiculo
50    59    51285
55    64    43261
23    27    39024
30    34    36897
31    35    33436
..   ...      ...
54    63     1853
9     13     1488
42    51      803
7     11      181
41    45       78

[65 rows x 2 columns]

In [51]:
array_veiculo_capital= np.array(df_veiculo_capital['veiculo']) #criação do Array

In [52]:
media = np.mean(array_veiculo_capital)
mediana = np.median(array_veiculo_capital)
q1 = np.quantile(array_veiculo_capital, 0.25)
q2 = np.quantile(array_veiculo_capital, 0.50)
q3 = np.quantile(array_veiculo_capital, 0.75)
iqr = q3 - q1
limite_superior = q3 + (1.5 * iqr) 
limite_inferior = q1 + (1.5 * iqr)
print(f'A média é {media}')
print(f'A mediana é {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, Mediana): {q2}')
print(f'Terceiro quartil (Q3): {q3}')
print(f'o valor do limite Superior é: {limite_superior}')
print(f'o valor do limite Inferior é: {limite_inferior}')

A média é 13949.333333333334
A mediana é 12701.0
Primeiro quartil (Q1): 5015.25
Segundo quartil (Q2, Mediana): 12701.0
Terceiro quartil (Q3): 18068.75
o valor do limite Superior é: 37649.0
o valor do limite Inferior é: 24595.5

In [ ]:
outliers_veiculo_capital = df_veiculo_capital[outliers_veiculo_capital]
#outliers_veiculo_capital = (df_veiculo_capital[veiculo] < limite_inferior) | (df_veiculo_capital[veiculo] > limite_superior)
df_veiculo_capital[outliers_veiculo_capital]

NameError: name 'outliers_veiculo_capital' is not defined